#! /bin/sh

sxhkd &
picom -CGb &
polybar bar &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 10

bspc rule -a Steam state=floating
bspd rule -a Wine state=floaing
